openapi: 3.0.0
info:
  title: FXLuminaire Luxor
  description: API specification for FXLuminaire's Luxor lighting system.
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0

servers:
- url: http://{host}
  variables:
    host:
      default: "localhost"

components:
  schemas:
    Status:
      type: integer
      format: uint8
      # oneOf:
      # - enum: [0]
      #   title: Ok
      # - enum: [1]
      #   title: UnknownMethod
      # - enum: [101]
      #   title: UnparseableRequest
      # - enum: [102]
      #   title: InvalidRequest
    Group:
      type: object
      properties:
        Grp:
          description: Group number
          type: integer
          format: uint8
        Name:
          type: string
        Inten:
          description: Intensity
          type: integer
          format: uint8
        Colr:
          description: Color
          type: integer
          format: uint8
    Theme:
      type: object
      properties:
        ThemeIndex:
          description: Theme number
          type: integer
          format: uint8
        Name:
          type: string
        OnOff:
          description: Color
          type: integer
          format: uint8
    ThemeGroup:
      type: object
      properties:
        GroupNumber:
          description: Group number
          type: integer
        Intensity:
          description: Intensity
          type: integer
          format: uint8
        Color:
          description: Color
          type: integer
          format: uint8

paths:
  /AssignLight.json:
    post:
      operationId: AssignLight
      tags:
        - Lights
      summary: "Assign a light to a group"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                SerialNumber:
                  type: integer
                GroupNumber:
                  type: integer
                  format: uint8
              required:
                - SerialNumber
                - GroupNumber
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ControllerName.json:
    post:
      operationId: ControllerName
      tags:
        - Controller
      summary: "Retrieve controller details"
      responses:
        '200':
          description: "Controller details"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
                  Controller:
                    type: string
                  ConnType:
                    type: string
                  RSSI:
                    type: integer

  /ExtinguishAll.json:
    post:
      operationId: ExtinguishAll
      tags:
        - Lights
      summary: "Turn off all lights"
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /FlashLights.json:
    post:
      operationId: FlashLights
      summary: "Flash all lights"
      tags:
        - Lights
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OnOff:
                  type: integer
                  format: uint8
              required:
                - OnOff
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /GroupListAdd.json:
    post:
      operationId: GroupListAdd
      tags:
        - Groups
      summary: "Add a group"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                GroupNumber:
                  type: integer
                  format: uint8
                Name:
                  type: string
              required:
              - GroupNumber
              - Name
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /GroupListClear.json:
    post:
      operationId: GroupListClear
      tags:
        - Groups
      summary: "TBD"
      responses:
        '200':
          description: "TBD"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
                  GroupList:
                    type: array
                    items:
                      $ref: '#/components/schemas/Group'

  /GroupListDelete.json:
    post:
      operationId: GroupListDelete
      tags:
        - Groups
      summary: "Delete a group"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
              required:
              - Name
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /GroupListGet.json:
    post:
      operationId: GroupListGet
      tags:
        - Groups
      summary: "Retrieve all groups"        
      responses:
        '200':
          description: "List of groups"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
                  GroupList:
                    type: array
                    items:
                      $ref: '#/components/schemas/Group'

  /GroupListRename.json:
    post:
      operationId: GroupListRename
      tags:
        - Groups
      summary: "Rename a group"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OldName:
                  type: string
                NewName:
                  type: string
              required:
              - OldName
              - NewName
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
  
  /GroupListReorder.json:
    post:
      operationId: GroupListReorder
      tags:
        - Groups
      summary: "Reorder all groups"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                GroupNumbers:
                  type: array
                  items:
                    type: integer
                    format: uint8
              required:
              - GroupNumbers
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /IlluminateAll.json:
    post:
      operationId: IlluminateAll
      tags:
        - Lights
      summary: "Turn on all lights"
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /IlluminateGroup.json:
    post:
      operationId: IlluminateGroup
      tags:
        - Groups
      summary: "Turn on a group of lights"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                GroupNumber:
                  type: integer
                  format: uint8
                Intensity:
                  type: integer
                  format: uint8
              required:
              - GroupNumber
              - Intensity
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /IlluminateTheme.json:
    post:
      operationId: IlluminateTheme
      tags:
        - Themes
      summary: "Activate a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndex:
                  type: integer
                  format: uint8
                OnOff:
                  description: "0 to turn off, or non-zero to set intensity"
                  type: integer
                  format: uint8
              required:
              - ThemeIndex
              - OnOff
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeClear.json:
    post:
      operationId: ThemeClear
      tags:
        - Themes
      summary: "TBD"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndex:
                  type: integer
                  format: uint8
              required:
              - ThemeIndex
      responses:
        '200':
          description: "Command result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeGet.json:
    post:
      operationId: ThemeGet
      tags:
        - Themes
      summary: "Retrieve a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndex:
                  type: integer
                  format: uint8
              required:
              - ThemeIndex
      responses:
        '200':
          description: "List of groups"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
                  Groups:
                    type: array
                    items:
                      $ref: '#/components/schemas/ThemeGroup'

  /ThemeListAdd.json:
    post:
      operationId: ThemeListAdd
      tags:
        - Themes
      summary: "Add a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndex:
                  type: integer
                  format: uint8
                Name:
                  type: string
              required:
              - ThemeIndex
              - Name
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeListClear.json:
    post:
      operationId: ThemeListClear
      tags:
        - Themes
      summary: "TBD"
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeListDelete.json:
    post:
      operationId: ThemeListDelete
      tags:
        - Themes
      summary: "Delete a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Name:
                  type: string
              required:
              - Name
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeListGet.json:
    post:
      operationId: ThemeListGet
      tags:
        - Themes
      summary: "Retrieve list of themes"
      responses:
        '200':
          description: "List of themes"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
                  Restricted:
                    description: "Restricted will be non-zero if themes are restricted in controller's setup menu. This implies some operations may not be performed through the API."
                    type: integer
                  ThemeList:
                    type: array
                    items:
                      $ref: '#/components/schemas/Theme'

  /ThemeListRename.json:
    post:
      operationId: ThemeListRename
      tags:
        - Themes
      summary: "Rename a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                OldName:
                  type: string
                NewName:
                  type: string
              required:
              - OldName
              - NewName
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'
  
  /ThemeListReorder.json:
    post:
      operationId: ThemeListReorder
      tags:
        - Themes
      summary: "Rename a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndexes:
                  type: array
                  items:
                    type: integer
                    format: uint8
              required:
              - ThemeIndexes
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

  /ThemeSet.json:
    post:
      operationId: ThemeSet
      tags:
        - Themes
      summary: "Activate a theme"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ThemeIndex:
                  type: array
                  items:
                    type: integer
                    format: uint8
                Groups:
                  type: array
                  items:
                    $ref: '#/components/schemas/ThemeGroup'
              required:
              - ThemeIndex
              - Groups
      responses:
        '200':
          description: "Command status"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    $ref: '#/components/schemas/Status'

    # Ok,
    # UnknownMethod,
    # UnparseableRequest,
    # InvalidRequest,
    # ColorValueOutOfRange,
    # PreconditionFailed,
    # GroupNameInUse,
    # GroupNumberInUse,
    # ItemDoesNotExist,
    # BadGroupNumber,
    # ThemeIndexOutOfRange,
    # BadThemeIndex,
    # ThemeChangesRestricted,
    # Unknown,
